version: "2.3"

services:
    postgres:
      container_name: service-postgres
      image: postgres:12
      environment:
        - POSTGRES_DB=test
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
      ports:
        - 8081:5432
      volumes:
        - ./postgresql/schemas:/docker-entrypoint-initdb.d
        - ./.pgdata:/var/lib/postgresql/data
    mysql:
      image: mysql
      container_name: service-mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: test
      volumes:
        - ./mysql/scripts:/docker-entrypoint-initdb.d
      ports:
        - "8082:3306"

